# Generated by Django 5.2.5 on 2025-08-31 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be exactly 11 digits.', regex='^0\\d{10}$')]),
        ),
    ]
