# Generated by Django 5.2.5 on 2025-09-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, default='بدون دسته بندی', related_name='products', to='products.category'),
        ),
    ]
