# Generated by Django 5.2.5 on 2025-09-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight_type',
            field=models.CharField(choices=[('geram', 'گرم'), ('kilo', 'کیلو')], default='geram', max_length=10),
        ),
    ]
