# Generated by Django 5.2.5 on 2025-09-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_weight_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight_type',
            field=models.CharField(choices=[('گرم', 'گرم'), ('کیلو', 'کیلو')], default='گرم', max_length=10),
        ),
    ]
