# Generated by Django 5.2.5 on 2025-09-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_weight_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shelf_life',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life_type',
            field=models.CharField(choices=[('روز', 'روز'), ('ساعت', 'ساعت'), ('ماه', 'ماه'), ('سال', 'سال')], default='روز', max_length=10),
        ),
    ]
