# Generated by Django 5.2.6 on 2025-09-09 09:26

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_shelf_life_product_shelf_life_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
