# Generated by Django 5.2.5 on 2025-09-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='ananymouse/ananymouse.jpg', null=True, upload_to='profiles/', verbose_name='پروفایل'),
        ),
    ]
