
@HOST = http://localhost:8000
@PHONE = 09123456787
@otp_code = 478248
@temp_token = c2264358-d161-4e8a-8659-a7d830a43258

### first step registration
POST {{HOST}}/auth/register/step-one/
Content-Type: application/json

{
  "phone_number": "{{PHONE}}"
}

### second step registration
POST {{HOST}}/auth/register/step-two/
Content-Type: application/json

{
  "otp_code": "{{otp_code}}",
  "temp_token": "{{temp_token}}"
}

### fisrt step login

POST {{HOST}}/auth/login/step-one/
Content-Type: application/json

{
  "phone_number": "{{PHONE}}"
}


### second step login
POST {{HOST}}/auth/login/step-two/
Content-Type: application/json

{
  "otp_code": "{{otp_code}}",
  "temp_token": "{{temp_token}}"
}

