
@HOST = http://localhost:8000
@PHONE = 09123456789
@otp_code = 444448
@temp_token = f7a6bf3f-659e-41fe-a260-922a302d24e7

### first step registration
POST {{HOST}}/auth/register/step-one/
Content-Type: application/json

{
  "phone_number": "{{PHONE}}"
}

### second step registration
POST {{HOST}}/auth/register/step-two/
Content-Type: application/json

{
  "otp_code": "{{otp_code}}",
  "temp_token": "{{temp_token}}"
}

### fisrt step login

POST {{HOST}}/auth/login/step-one/
Content-Type: application/json

{
  "phone_number": "{{PHONE}}"
}


### second step login
POST {{HOST}}/auth/login/step-two/
Content-Type: application/json

{
  "otp_code": "{{otp_code}}",
  "temp_token": "{{temp_token}}"
}

