@HOST = http://0.0.0.0:8000

@PHONE = 09123456789

###
# fisrt steo login
@otp_code = 118587
@temp_token = 1586c69a-5c5b-47b3-83fa-be4db5c24179
POST {{HOST}}/auth/login/step-one/
Content-Type: application/json

{
  "phone_number": "{{PHONE}}"
}


###
# second step login
POST {{HOST}}/auth/login/step-two/
Content-Type: application/json

{
  "otp_code": "{{otp_code}}",
  "temp_token": "{{temp_token}}"
}


# "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTAzOTczODE2MTUsImlhdCI6MTc1NzQ2ODAxNSwianRpIjoiOWFiZWNhOTMzMjYzNGFlNGE5YzhiMzdlYzBkZDY4MGQiLCJ1c2VyX2lkIjoiNzAifQ.1-3YxHjQTwlPctcp-YDrMb1YQoETbgL-cVGPwQzwVjI",
#   "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxMDM5NzM4MTYxNSwiaWF0IjoxNzU3NDY4MDE1LCJqdGkiOiIyNDhlYjhkMzU3MDg0ZDA1YTIyNmYxN2I3ZWU1MDI5ZSIsInVzZXJfaWQiOiI3MCJ9.4YM3CxtOcNPDUqYmMPZTX6JoJ4fovebT1r8jGsMvanw",

