
@HOST = http://localhost:8000
@PHONE = 09123456789
### first step registration
@otp_code = 103814
@temp_token = e428dcc8-c5b8-49bd-a659-f78456c00f7f
POST {{HOST}}/auth/register/step-one/
Content-Type: application/json

{
  "phone_number": "{{PHONE}}"
}

### second step registration
POST {{HOST}}/auth/register/step-two/
Content-Type: application/json

{
  "otp_code": "{{otp_code}}",
  "temp_token": "{{temp_token}}"
}
